   services:
       db:
         image: postgres:12
         container_name: db
         restart: always
         environment:
           - POSTGRES_DB=bs_db
           - POSTGRES_USER=ordinary_user
           - POSTGRES_PASSWORD=pass1234
         volumes:
           - pgdata:/var/lib/postgresql/data
         ports:
           - "5432:5432"
         networks:
           - djangonetwork
       webdjango:
         build: .
         container_name: django
         command: >
              sh -c " python manage.py makemigrations;
              python manage.py migrate;
              python manage.py runserver 0.0.0.0:8000"
        #  command: python manage.py runserver 0.0.0.0:8000
         volumes:
           - .:/bs_app
         ports:
           - "8000:8000"
         environment:
           - POSTGRES_NAME=bs_db
           - POSTGRES_USER=ordinary_user
           - POSTGRES_PASSWORD=pass1234
         depends_on:
           - db
         links:
           - db:db
         networks:
           - djangonetwork
   networks:
       djangonetwork:
         driver: bridge
   volumes:
     pgdata:
